# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: nest-test-app
    build:
      context: .
    volumes:
      - ./:/app
    command: yarn start:dev
    ports:
      - 3000:3000

  mongo:
    image: mongo
    container_name: nest-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db